//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class linkfriendcategory
    {
        public int Id { get; set; }
        public string IdFriend { get; set; }
        public int IdCategory { get; set; }
        public string Tag { get; set; }
    
        public virtual category category { get; set; }
        public virtual friend friend { get; set; }
    }
}
