//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.words = new HashSet<word>();
            this.linkfriendcategories = new HashSet<linkfriendcategory>();
        }
    
        public int Id { get; set; }
        public string Category1 { get; set; }
    
        public virtual ICollection<word> words { get; set; }
        public virtual ICollection<linkfriendcategory> linkfriendcategories { get; set; }
    }
}
