//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentsuser
    {
        public short Id { get; set; }
        public string PhotoId { get; set; }
        public string UserId { get; set; }
        public string CommentatorId { get; set; }
        public string Comment { get; set; }
    }
}
