//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class linkusercategory
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int Category { get; set; }
        public string Tag { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual user user { get; set; }
    }
}
