//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_F
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class flickr_tablesEntities : DbContext
    {
        public flickr_tablesEntities()
            : base("name=flickr_tablesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<linkfriend> linkfriends { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<word> words { get; set; }
        public DbSet<friendtag> friendtags { get; set; }
        public DbSet<friend> friends { get; set; }
        public DbSet<linkfriendcategory> linkfriendcategories { get; set; }
        public DbSet<commentsuser> commentsusers { get; set; }
        public DbSet<usertag> usertags { get; set; }
        public DbSet<linkusercategory> linkusercategories { get; set; }
    }
}
